name: bike-discount-crawler
services:
  redis:
    container_name: redis
    image: redis:7.2-alpine
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=my-password
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
  app:
    container_name: app
    build: ./
    ports:
      - "3000:3000"
    environment:
      - REDIS_URL=redis://default:my-password@redis:6379/0
      - QUEUE_HOST=redis
      - QUEUE_PORT=6379
      - QUEUE_PASSWORD=my-password
      - AUTH_USERNAME=admin
      - AUTH_PASSWORD=admin
      - AUTH_SECRET=test_auth_secret
    depends_on:
      - redis
networks:
  default:
    name: wp-plugins_default
    external: true